//
//  SplashInteractor.swift
//  TestGit
//
//  Created by Игорь Дикань on 22.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashBusinessLogic {
    func make(request: Splash.Model.Request.RequestType)
}

protocol SplashDataStore: class {
    //var name: String { get set }
}

final class SplashInteractor {
    
    // MARK: - External vars
    var presenter: SplashPresentationLogic?
    var worker: SplashWorker?
    //var name: String = ""
    
    // MARK: - Internal vars
    
    init() {
        
    }
    
}

// MARK: - Business logic
extension SplashInteractor: SplashBusinessLogic {
    
    func make(request: Splash.Model.Request.RequestType) {
        switch request {
        case .some:
            print("SplashInteractor")
            presenter?.presentData(response: .some)
        }
    }
}

// MARK: - Data store
extension SplashInteractor: SplashDataStore {
    
}
