//
//  SplashRouter.swift
//  TestGit
//
//  Created by Игорь Дикань on 22.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashRoutingLogic {
    
}

protocol SplashDataPassing {
    var dataStore: SplashDataStore? { get }
}

final class SplashRouter: NSObject {
    
    // MARK: - External vars
    weak var viewController: SplashViewController?
    weak var dataStore: SplashDataStore?
}

// MARK: - Routing logic
extension SplashRouter: SplashRoutingLogic {
    
}

// MARK: - Data passing
extension SplashRouter: SplashDataPassing {
    
}
