//
//  MainModels.swift
//  TestGit
//
//  Created by Игорь Дикань on 22.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
  
    enum Model {
        struct Request {
            enum RequestType {
                case some
            }
        }
        struct Response {
            enum ResponseType {
                case some
            }
        }
        struct ViewModel {
            enum ViewModelType {
                case some
            }
        }
    }
}
