//
//  MainPresenter.swift
//  TestGit
//
//  Created by Игорь Дикань on 22.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentData(response: Main.Model.Response.ResponseType)
}

final class MainPresenter {
    
    // MARK: - External vars
    weak var viewController: MainDisplayLogic?
}

// MARK: - Presentation logic
extension MainPresenter: MainPresentationLogic {
    
    func presentData(response: Main.Model.Response.ResponseType) {
        switch response {
        case .some:
            print("MainViewController")
            viewController?.display(viewModel: .some)
        }
    }
}
