//
//  MainInteractor.swift
//  TestGit
//
//  Created by Игорь Дикань on 22.03.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func make(request: Main.Model.Request.RequestType)
}

protocol MainDataStore: class {
    //var name: String { get set }
}

final class MainInteractor {
    
    // MARK: - External vars
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    //var name: String = ""
    
    // MARK: - Internal vars
    
    init() {
        
    }
    
}

// MARK: - Business logic
extension MainInteractor: MainBusinessLogic {
    
    func make(request: Main.Model.Request.RequestType) {
        switch request {
        
        }
    }
}

// MARK: - Data store
extension MainInteractor: MainDataStore {
    
}
